[project]
name = "logging-module"
version = "1.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.ruff.lint]
extend-select = ["PTH"]
